# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  proyecto: 'WebAPIAutores/WebAPIAutores.csproj'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 7.0.100'
    inputs:
      version: '7.0.100'
      includePreviewVersions: true

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Installing EF Core CLI'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'dotnet tool install --global dotnet-ef'

  - task: DotNetCoreCLI@2
    displayName: 'Generating DB script'
    inputs:
      command: 'custom'
      custom: 'ef'
      arguments: 'dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)\migrate.sql --project $(proyecto)'

- job: Publish
  displayName: 'Publish job'
  dependsOn: Build
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Publishing App...'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: $(proyecto)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x64 --self-contained'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publishing artifacts'
